### ISSUE TITLE
Docs are not updated

### ISSUE THREAD

**Issue by alnutile** [SocialiteProviders/Documentation#25]
The docs here 
http://socialiteproviders.netlify.com/providers/okta.html#add-to-config-services-php

```
'okta' => [
    'client_id' => env('OKTA_KEY'),
    'client_secret' => env('OKTA_SECRET'),
    'redirect' => env('OKTA_REDIRECT_URI')
],
```

Are missing what is here 
https://github.com/SocialiteProviders/Documentation/blob/master/docs/providers/okta.md#add-to-configservicesphp 

```
'okta' => [
    'client_id' => env('OKTA_KEY'),
    'client_secret' => env('OKTA_SECRET'),
    'redirect' => env('OKTA_REDIRECT_URI'),
    'base_url' => env('OKTA_BASE_URL')
],
```

Which is key since without the base_url this will not work

Does someone need to merge these?

**Comment by m1guelpf** [comment]
Moved to Netlify & fixed
