### ISSUE TITLE
Confusing navigation

### ISSUE THREAD

**Issue by jasonmccallister** [SocialiteProviders/Documentation#4]
When looking at the documentation for this package, I always have to "double take" the navigation. When I am looking for a provider, clicking the about navigation item does not make sense. 

Would you accept a PR that updates about to Providers?

**Comment by m1guelpf** [comment]
@jasonmccallister Yeah, go ahead!

**Comment by m1guelpf** [comment]
@jasonmccallister Any updates on this?
