### ISSUE TITLE
$additionalProviderConfig = ['site' => 'meta.stackoverflow.com'];

### ISSUE THREAD

**Issue by spekulatius** [SocialiteProviders/Documentation#43]
Hello @m1guelpf 

all providers have:

    $additionalProviderConfig = ['site' => 'meta.stackoverflow.com'];

in their doc - it comes from the generator template. Should I open a PR to remove it?

Cheers,
Peter

**Comment by m1guelpf** [comment]
Yes please!

**Comment by spekulatius** [comment]
Done @m1guelpf , have a look at #44 - it cleans it up and breaks it down a little more to avoid a scrollbar 👍️
