### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by Jimbolino** [SocialiteProviders/Documentation#47]
Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

on the root page: https://socialiteproviders.netlify.com/

**Comment by shaunthegeek** [comment]
this docs repo build failed, maybe the reason is `build/split.sh` not run in https://github.com/SocialiteProviders/Providers/issues/304
@m1guelpf 
404:  https://github.com/SocialiteProviders/ClaveUnica

```
npm run docs:build
Rendering static HTML...
Rendering page: /[vuepress] No matching page found for sidebar item "/providers/clave-unica"
Error rendering /:
TypeError: Cannot read property 'match' of undefined
    at getHash (docs/.vuepress/theme/util.js:13:21)
```
