### ISSUE TITLE
Dropbox 

### ISSUE THREAD

**Issue by rohstar** [SocialiteProviders/Documentation#59]
In the documentation, [here](https://socialiteproviders.netlify.com/providers/dropbox.html), it is mentioned that: 

`return Socialite::with('Dropbox')->stateless()->redirect();`

is the code to make dropbox work, but that gave me an error. I was able to resolve this by replacing with a lowercase D in the "with" method: 

`return Socialite::with('dropbox')->stateless()->redirect();`

For anyone else having that issue, I'm leaving this here.

**Comment by m1guelpf** [comment]
Feel free to PR the update

**Comment by rohstar** [comment]
> Feel free to PR the update

https://github.com/SocialiteProviders/Documentation/pull/65
