### ISSUE TITLE
Update docs and other issues

### ISSUE THREAD

**Issue by Paulsky** [SocialiteProviders/Documentation#69]
For everyone who just started with this project. I found out the following:

- ~~CoinBase is not working: https://github.com/SocialiteProviders/Providers/issues/356~~ Fixed: https://github.com/SocialiteProviders/Providers/pull/357
- Reddit is working, but the API is not returning an email address! So don't bother with it if you need the email address of the User
- Use the correct Microsoft Provider. See this issue: https://github.com/SocialiteProviders/Documentation/issues/68
- Use the correct Google Provider. See this issue and comment: https://github.com/SocialiteProviders/Providers/issues/281#issuecomment-548297327

**Comment by m1guelpf** [comment]
I'd be happy to accept PRs that solve any of this issues!

**Comment by Paulsky** [comment]
- Shall I update the Reddit documentation?
- I have asked the author of the 'new' Microsoft provider if he could add documentation for the provider (https://github.com/SocialiteProviders/Providers/pull/130#issuecomment-562957285), after the new documentation, I could update the old Microsoft Provider documentation with a deprecated notice?
- Could you please have a look at the Google Provider issue? I'm not sure how and what to fix. If I do, I would happily create a PR for this
